In [1]:
import numpy as np # it use for mathematical fuctions in pandas

In [2]:
#SERIES: ONLY ONE COL  ----ex-1D array
#DATAFRAME: MANY RO MANY COL IE.ITS CALLED DATA ---------ex-2D array
# MANY SERIES COMBINE ITS SHOULD BE  CALLED DATA FRAME 

In [3]:
import pandas as pd


In [4]:
#1.series is a one dimesional array with homogenoues
#key point of series
#   it is immutable  ie. row  of col we cant add or update its index cant update
#values of data mutable means change the value of data ie. we cant add any row and col but we can chnage the row value like index 0 value is annu can change another name 

In [5]:
# create an Empty series
A=pd.Series()# bydefault tyoe float64
print(A)

Series([], dtype: float64)


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  


In [6]:
#create a serias from list
data=[45,67,89,23] #data user defined list object
print(data)

[45, 67, 89, 23]


In [7]:
marks=pd.Series(data)#converts list into sereis(1-D array)
print(marks)

0    45
1    67
2    89
3    23
dtype: int64


In [8]:
#create a series from ndarray(use in numpy) 
data=np.array([34,1,45,67,78])#1D array create from numpy array 
print(data)


[34  1 45 67 78]


In [9]:
#covert 1D numpy array to series in pandas 
A=pd.Series(data)
print(A)

0    34
1     1
2    45
3    67
4    78
dtype: int32


In [10]:
#create a series from ndarray(use in numpy) 
data=np.array([34,1,45,67,78])#1D array create from numpy array 
print(data)

[34  1 45 67 78]


In [11]:
A=pd.Series(data)
print(data)

[34  1 45 67 78]


In [12]:
A=pd.Series(data,index=[100,101,102,103,104]) # here we give index value ,if not given  bydeault it can take from 0 to end 

In [13]:
print(A)

100    34
101     1
102    45
103    67
104    78
dtype: int32


In [14]:
A[101] #To access value at index 101

1

In [15]:
A[101]=67 #update value 76 of index 101

In [16]:
print(A)

100    34
101    67
102    45
103    67
104    78
dtype: int32


In [17]:
#Example  of series means 1D array
#we create a list (list means collection same or mixed datatype in single object)
L=['Anamika',22,'Mumbai',8783748745]

In [18]:
print(L)

['Anamika', 22, 'Mumbai', 8783748745]


In [19]:
#convert this list L into Series of pandas
S=pd.Series(L,index=['Name','Age','City','Mobile'])
print(S)

Name         Anamika
Age               22
City          Mumbai
Mobile    8783748745
dtype: object


In [20]:
#access the name of student
S['Name']

'Anamika'

In [21]:
#access name and city and age (multilpe col)  means 2D array
#use [[]]
S[['Name','Age','City']]

Name    Anamika
Age          22
City     Mumbai
dtype: object

In [22]:
#To hold data in dictionary in python key and value 
data={'Name':'Anamika','Age':22,'City':'Mumbai','Mobile':688767888}
print(data)

{'Name': 'Anamika', 'Age': 22, 'City': 'Mumbai', 'Mobile': 688767888}


In [23]:
#covert this dictionary into Series pandas     # dictionary comes in 2D but its work on  only smalls data 
S=pd.Series(data)# here key work like index 

In [24]:
print(S)

Name        Anamika
Age              22
City         Mumbai
Mobile    688767888
dtype: object


In [25]:
#DataFrame in pandas means create 2 D arry means many student many row
#and each row ,many coloumn
#DataFrame is a main structure 
#DataFrame is store dat in tubular form 
# mny details of many student then use DataFrame
#but create dictionaryin python
dict1={"Name":['Annu','Arush','ishika','fareen',],"Maths":[56,67,89,23],"Science":[45,67,89,23],"City":["Mumbai","chennai","Usa","America"]}

In [26]:
print(dict1)

{'Name': ['Annu', 'Arush', 'ishika', 'fareen'], 'Maths': [56, 67, 89, 23], 'Science': [45, 67, 89, 23], 'City': ['Mumbai', 'chennai', 'Usa', 'America']}


In [27]:
#Converts these dictionary dict1 into dataframe of pandas
student=pd.DataFrame(dict1)#student user defined object of DataFrame
print(student)

     Name  Maths  Science     City
0    Annu     56       45   Mumbai
1   Arush     67       67  chennai
2  ishika     89       89      Usa
3  fareen     23       23  America


In [28]:
#access data from data frame student
#access all details (all coloumns) of index 1
student.iloc[1] #iloc index location row index location


Name         Arush
Maths           67
Science         67
City       chennai
Name: 1, dtype: object

In [29]:
student.iloc[2]


Name       ishika
Maths          89
Science        89
City          Usa
Name: 2, dtype: object

In [30]:
student.loc[1,"Maths"]# only access 1 col i.e arush 1maths  mark =67 ,,, if we dont know index of col then we write col name we use loc only

67

In [31]:
student.iloc[1,1]# if we know col index then we use i loc i.e index location

67

In [32]:
print(student.columns)# to show columns name 

Index(['Name', 'Maths', 'Science', 'City'], dtype='object')


In [33]:
#another way of same process
student["Maths"][1]

67

In [34]:
print(student)

     Name  Maths  Science     City
0    Annu     56       45   Mumbai
1   Arush     67       67  chennai
2  ishika     89       89      Usa
3  fareen     23       23  America


In [35]:
#access data through slicing means :
# suppose access all details(all columns of rowindex= and 2 )
student.iloc[1:3,:]#here iloc[row startindex:stopindex,col start:col end] col no given means all access

Name  Maths  Science     City
1   Arush     67       67  chennai
2  ishika     89       89      Usa

In [36]:
#suppose access details of Maths,Science and City of  rowindex =1 and 2 ) 
student.iloc[1:3,1:]   #here [rowstart:row stop , colstart:till end]

Maths  Science     City
1     67       67  chennai
2     89       89      Usa

In [37]:
student.iloc[1:,:2] #[ro3 st=1 :sp=all , col st:0 : sp=2 i.e 2-1]

Name  Maths
1   Arush     67
2  ishika     89
3  fareen     23

In [41]:
print(student)

     Name  Maths  Science     City
0    Annu     56       45   Mumbai
1   Arush     67       67  chennai
2  ishika     89       89      Usa
3  fareen     23       23  America


In [43]:
S1=student.drop("City",axis=1)# to copy name ,maths and science col of all student from data frame student 
#to new dataframe S1    is drop col then write axis =1 bcoz its go right to left ---->>
                        #is drop row  then write axis =0 bcoz its go top to bottom |
print(S1)              #                                                          |

     Name  Maths  Science
0    Annu     56       45
1   Arush     67       67
2  ishika     89       89
3  fareen     23       23


In [44]:
#another way : #to copy Name,Maths and Science columns of all students from data frame student 
#to new dataframe S1
S1=student.iloc[:,:-1] # [0:tillend , 0:-2] stop-1=-1-1=-2  we use for only del last col of data
print(S1)

     Name  Maths  Science
0    Annu     56       45
1   Arush     67       67
2  ishika     89       89
3  fareen     23       23
